from enum import Enum

class ExpTiers(Enum):
  CHALLENGER="CHALLENGER"
  GRANDMASTER="GRANDMASTER"
  MASTER="MASTER"
  DIAMOND="DIAMOND"
  PLATINUM="PLATINUM"
  GOLD="GOLD"
  SILVER="SILVER"
  BRONZE="BRONZE"
  IRON="IRON"

